version: '3.8'

services:
  nodejs: 
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs:latest
    container_name: sd-app
    restart: "no"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
      - sqlite_data:/app/db
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - SQLITE_DB_PATH=/app/db/database.sqlite
    networks:
      sd-network:
        ipv4_address: 172.23.0.3

volumes:
  sqlite_data:

networks:
  sd-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24
